const FF7_USER_SAVE_DIR = 10;
const FF7_DOC_DIR = 11;
const FF7_INSTALL_DIR = 12;
const FF7_LOCALE_DATA_DIR = 13;
const FF7_GAME_VERSION = 18;
const FF7_DISABLE_CLOUD = 22;
const FF7_END_USER_INFO = 24;

const FF8_USER_SAVE_DIR = 9;
const FF8_DOC_DIR = 10;
const FF8_INSTALL_DIR = 11;
const FF8_LOCALE_DATA_DIR = 12;
const FF8_GAME_VERSION = 17;
const FF8_DISABLE_CLOUD = 21;
const FF8_BG_PAUSE_ENABLED = 23;
const FF8_END_USER_INFO = 24;

const ESTORE_USER_SAVE_DIR = 9;
const ESTORE_DOC_DIR = 10;
const ESTORE_INSTALL_DIR = 11;
const ESTORE_LOCALE_DATA_DIR = 12;
const ESTORE_GAME_VERSION = 17;
const ESTORE_END_USER_INFO = 20;

